version: '3'
services:
  postgre-dev:
    image: postgres:latest
    container_name: postgres_dev
    restart: unless-stopped
    hostname: postgres_dev
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS='--encoding=UTF-8'
    ports:
      - 3254:5432
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data
      # - pgconf:/etc/postgresql
      - ./data/pglog:/var/log/postgresql
      # - data:/var/lib/postgresql/data
    networks:
      - pgnet

  pgadmin4-dev:
    image: dpage/pgadmin4
    container_name: pgadmin4_dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '9090:80'
    volumes:
      - ./pgadmin:/root/.pgadmin
    depends_on:
      - postgre-dev
    networks:
      - pgnet

networks:
  pgnet:
    driver: bridge
# volumes:
#   data: {}
