version: '3'
services:
  mongo-dev:
    image: mongo:latest
    container_name: mongo_dev
    restart: unless-stopped
    hostname: mongo_dev
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}
    ports:
      - 17270:27017
    command: ['-f', '/etc/mongod.conf']
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./data/db:/data/db
      - ./data/log:/var/log/mongodb
